[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_type = "semver"
version = "0.8.0"
update_changelog_on_bump = true
major_version_zero = true
version_files = [
    "Cargo.toml:^version",
    "crates/recp/Cargo.toml:^recipe-parser",
]